### PR TITLE
Market Period Enum Added and some tests

### PR DESCRIPTION
**Pull request by InTheta**
Market Period Enum Added and some tests

### CODE REVIEW

**Review by InTheta — COMMENTED** [review]
Data is returning OK, its the sandbox data which is all over the place.

**Comment by ChristopherHaws** [comment]
Thanks for the PR. I am working on getting an automated build setup, so I will probably not be able to merge this PR until this weekend. I am also working on making it easier to write unit tests without having to use the sandbox site since those wont be able to run in the automated build. I will probably make a second test project for integration tests that wont run as part of the CI.

**Comment by InTheta** [comment]
Sounds good.

Need to implement websocket too. I don't really need it right now, everything else I have needed for a project I'm working on.

Only major change is the MarketPeriod Enum addition.

The rest was cleaning up the test files.

All the best

**Comment by ChristopherHaws** [comment]
I think that it might make more sense to use TimeSpan instead of an enum for the period. Then consumers aren't locked into the values in the enum.

**Comment by InTheta** [comment]
You will 95% of the time you will use a standard chart period.

You don't need a 7 min chart etc.
Standard charting periods are more useful I would say.

Just my opinion.

**Pull request closed without merging**
